version: '3'

networks:
  consul-network:
    driver: bridge
    external: false

services:

  bgps:
    image: arina/bgps:master
    container_name: bgps
    hostname: bgps
    ports:
      - 8000:8000
    networks:
      - consul-network
    restart: unless-stopped


